<a href="https://colab.research.google.com/github/Benbuk/GOMYCODE_DS_Bootcamp/blob/main/Data_pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Checkpoint Objective**

In this checkpoint, we are going to work on the billing history of the Tunisian electricity and gas company and apply what you learned in pre-processing chapter.

Dataset description :

The provided dataset contains the billing history of the Tunisian electricity and gas company's customers from 2005 to 2019.

[Dataset](https://drive.google.com/file/d/1DVFNq8Gsf9wFZznGafhykVmVHLvAclGo/view?usp=drivesdk)


Instructions
1. Load the dataset, display the ten first lines, store the results in a variable called 'client_0_bills'.
1. What is the data type of the 'client_0_bills' variable ?
2. Display the general information of the dataset and try to answer the following questions :
>How many rows and columns do we have in this dataset?
>How many categorical features are present in the dataset?
>How much memory space does the dataset consume ?
6. Inspect the dataset for potential missing values.
7. Select your strategy to handle missing values, and tell us why you had made that choice.
8. Run a descriptive analysis on numeric features (columns).
9. Select the bills records for the client with an id ='train_Client_0', using 2 methods.
10. Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
11. Delete the 'counter_statue' feature from the Dataframe

*Importing Pandas Library and the dataset for preprocessing*

In [58]:
import pandas as pd
file_path = "/content/STEG_BILLING_HISTORY.csv"
STEG_BILLING_HISTORY = pd.read_csv(file_path)

<ipython-input-58-5b5428e1bea3>:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  STEG_BILLING_HISTORY = pd.read_csv(file_path)

*The overall datatype of the client_0_bills variable is object*

In [53]:
#selecting the first 10 rows of the dataset
client_0_billS = STEG_BILLING_HISTORY[0:10]
client_0_billS

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [60]:
#datatype of the variable
client_0_billS.dtypes

client_id                object
invoice_date             object
tarif_type                int64
counter_number          float64
counter_statue           object
counter_code              int64
reading_remarque        float64
counter_coefficient       int64
consommation_level_1      int64
consommation_level_2      int64
consommation_level_3      int64
consommation_level_4      int64
old_index                 int64
new_index                 int64
months_number             int64
counter_type             object
dtype: object

Below set of codes provides some basic information about the dataset.

There are;
> 4476749 rows and 16 columns

> Four categorical columns with the object data types

> The dataset occupies a space of 546.5 MB

In [63]:
STEG_BILLING_HISTORY.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_code          int64
 5   reading_remarque      float64
 6   counter_coefficient   int64
 7   consommation_level_1  int64
 8   consommation_level_2  int64
 9   consommation_level_3  int64
 10  consommation_level_4  int64
 11  old_index             int64
 12  new_index             int64
 13  months_number         int64
 14  counter_type          object
 15  counter_type_encoded  int64
dtypes: float64(2), int64(11), object(3)
memory usage: 546.5+ MB

In [62]:
STEG_BILLING_HISTORY.shape

(4476749, 16)

Only two columns has null values.
> The counter_number column wuth 48 null values

> The reading_remarque column with 4531 values

To handle the null values, dropna() was used as opposed to using fillna() with mean, median or z-score because the of the number of missing is relatively low compared to the entire dataset with over 4million observation. So, dropping the null values wont have much impact on the results.

In [64]:
STEG_BILLING_HISTORY.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
counter_type_encoded       0
dtype: int64

In [39]:
STEG_BILLING_HISTORY.dropna()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4476744,train_Client_99998,2005-08-19,10,1253571.0,0,202,9.0,1,400,135,0,0,3197,3732,8,ELEC
4476745,train_Client_99998,2005-12-19,10,1253571.0,0,202,6.0,1,200,6,0,0,3732,3938,4,ELEC
4476746,train_Client_99999,1996-09-25,11,560948.0,0,203,6.0,1,259,0,0,0,13884,14143,4,ELEC
4476747,train_Client_99999,1996-05-28,11,560948.0,0,203,6.0,1,603,0,0,0,13281,13884,4,ELEC
4476748,train_Client_99999,1996-01-25,11,560948.0,0,203,6.0,1,516,0,0,0,12765,13281,4,ELEC

The code chunk shows the descriptive statistics of the numerical columns of this dataset

In [38]:
# Descriptive Statistics
STEG_BILLING_HISTORY.describe()

,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,4.476749e+06,4.476701e+06,4.476749e+06,4.472218e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06
mean,2.012804e+01,1.230595e+11,1.724884e+02,7.321713e+00,1.003040e+00,4.109795e+02,1.093225e+02,2.030620e+01,5.292588e+01,1.776700e+04,1.834970e+04,4.483095e+01
std,1.347256e+01,1.657276e+12,1.338871e+02,1.571859e+00,3.083466e-01,7.573080e+02,1.220123e+03,1.574239e+02,8.754725e+02,4.036693e+04,4.095321e+04,3.128335e+03
min,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.100000e+01,1.211080e+05,5.000000e+00,6.000000e+00,1.000000e+00,7.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.791000e+03,2.056000e+03,4.000000e+00
50%,1.100000e+01,4.945610e+05,2.030000e+02,8.000000e+00,1.000000e+00,2.740000e+02,0.000000e+00,0.000000e+00,0.000000e+00,7.690000e+03,8.192000e+03,4.000000e+00
75%,4.000000e+01,1.115161e+06,2.070000e+02,9.000000e+00,1.000000e+00,6.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,2.166000e+04,2.234300e+04,4.000000e+00
max,4.500000e+01,2.798115e+13,6.000000e+02,4.130000e+02,5.000000e+01,9.999100e+05,9.990730e+05,6.449200e+04,5.479460e+05,2.800280e+06,2.870972e+06,6.366240e+05

In [65]:
#Using the groupby function to get the descriptive statistics of the categorical data in the counter_type column

STEG_BILLING_HISTORY.groupby('counter_type').mean()

<ipython-input-65-76c6453e9d29>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  STEG_BILLING_HISTORY.groupby('counter_type').mean()

,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type_encoded
counter_type,,,,,,,,,,,,,
ELEC,11.082348,1.788990e+11,248.317754,7.374830,1.004396,507.918803,158.122399,29.520556,76.942075,23230.973855,23951.776480,21.813730,0.0
GAZ,40.062556,4.003179e+06,5.378940,7.204652,1.000052,197.348707,1.779250,0.000000,0.000000,5725.717599,6004.093216,95.555325,1.0

In [66]:
# Selecting the bill information fir the client with id number
# Method 1
STEG_BILLING_HISTORY[STEG_BILLING_HISTORY['client_id'] == 'train_Client_0']
# Method 2
STEG_BILLING_HISTORY = STEG_BILLING_HISTORY.query("client_id == 'train_Client_0'")

The co chunk below encodes the counter_type column and deltes the counter_statue column.

In [59]:
# Transform 'counter_type' feature to a numeric variable (example: using LabelEncoder)
from sklearn.preprocessing import LabelEncoder

STEG_BILLING_HISTORY['counter_type_encoded'] = LabelEncoder().fit_transform(STEG_BILLING_HISTORY['counter_type'])

# Delete the 'counter_statue' feature
STEG_BILLING_HISTORY = STEG_BILLING_HISTORY.drop('counter_statue', axis=1)

print(STEG_BILLING_HISTORY.head())

        client_id invoice_date  tarif_type  counter_number  counter_code  \
0  train_Client_0   2014-03-24          11       1335667.0           203
1  train_Client_0   2013-03-29          11       1335667.0           203
2  train_Client_0   2015-03-23          11       1335667.0           203
3  train_Client_0   2015-07-13          11       1335667.0           207
4  train_Client_0   2016-11-17          11       1335667.0           207

   reading_remarque  counter_coefficient  consommation_level_1  \
0               8.0                    1                    82
1               6.0                    1                  1200
2               8.0                    1                   123
3               8.0                    1                   102
4               9.0                    1                   572

   consommation_level_2  consommation_level_3  consommation_level_4  \
0                     0                     0                     0
1                   184                     0                     0
2                     0                     0                     0
3                     0                     0                     0
4                     0                     0                     0

   old_index  new_index  months_number counter_type  counter_type_encoded
0      14302      14384              4         ELEC                     0
1      12294      13678              4         ELEC                     0
2      14624      14747              4         ELEC                     0
3      14747      14849              4         ELEC                     0
4      15066      15638             12         ELEC                     0